const tutors = [
  {id:"maya",name:"Maya Chen",subjects:["Math","Algebra"],grades:"Grades 6–10",rate:50,availability:["Mon · 4:00 PM","Wed · 5:30 PM","Sat · 10:00 AM"],color:"#f6c9b8",bio:"Maya helps students turn intimidating problems into small, manageable steps. She brings five years of middle-school classroom experience."},
  {id:"jordan",name:"Jordan Brooks",subjects:["Science","Math"],grades:"Grades 5–9",rate:45,availability:["Tue · 4:30 PM","Thu · 6:00 PM","Sat · 1:00 PM"],color:"#c8dfd2",bio:"Jordan makes science hands-on and memorable, connecting new ideas to the everyday world. Students appreciate his calm, curious approach."},
  {id:"sofia",name:"Sofia Martinez",subjects:["Reading","Elementary Math"],grades:"Grades K–6",rate:40,availability:["Mon · 3:30 PM","Fri · 4:00 PM","Sun · 11:00 AM"],color:"#f4dda9",bio:"Sofia builds strong foundations through encouragement, stories, and plenty of celebration. She specializes in helping younger learners gain confidence."},
  {id:"marcus",name:"Marcus Reed",subjects:["Algebra","Science"],grades:"Grades 8–12",rate:55,availability:["Tue · 6:30 PM","Thu · 5:00 PM","Sun · 2:00 PM"],color:"#cbd5ef",bio:"Marcus helps older students connect the dots in algebra and science. His sessions balance clear explanations with independent problem-solving."}
];
const STORAGE_KEY="abc-tutoring-bookings-v1",HOLD_MS=24*60*60*1000;

function portrait(t){const skin=t.id==="maya"?"#e4aa83":t.id==="jordan"?"#81543d":t.id==="sofia"?"#c98762":"#6d452f";return `<svg viewBox="0 0 220 200" role="img" aria-label="Sample portrait of ${t.name}"><circle cx="110" cy="82" r="48" fill="${skin}"/><path d="M65 75q5-56 47-55 44 2 47 57-18-17-32-30-18 21-62 28" fill="#283934"/><circle cx="93" cy="84" r="3"/><circle cx="128" cy="84" r="3"/><path d="M99 105q12 9 24 0" fill="none" stroke="#784533" stroke-width="3" stroke-linecap="round"/><path d="M42 200q8-70 68-70t68 70" fill="#287358"/><path d="M93 129l17 20 18-20" fill="#fff" opacity=".8"/></svg>`}
function loadBookings(){const all=JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]");const now=Date.now();let changed=false;all.forEach(b=>{if(b.status==="pending"&&now-b.createdAt>HOLD_MS){b.status="expired";changed=true}});if(changed)saveBookings(all);return all}
function saveBookings(items){localStorage.setItem(STORAGE_KEY,JSON.stringify(items))}
function unavailable(tutorId){return new Set(loadBookings().filter(b=>b.tutorId===tutorId&&["pending","approved"].includes(b.status)).map(b=>b.slot))}
function capture(event,properties={}){const safe={...properties,prototype:"abc-tutoring"};if(window.posthog?.capture&&window.ABC_CONFIG?.posthogKey&&!window.ABC_CONFIG.posthogKey.includes("REPLACE")){window.posthog.capture(event,safe)}else{console.info("[analytics]",event,safe)}}
function initAnalytics(){const c=window.ABC_CONFIG||{};if(window.posthog?.init&&c.posthogKey&&!c.posthogKey.includes("REPLACE")){window.posthog.init(c.posthogKey,{api_host:c.posthogHost||"https://us.i.posthog.com",person_profiles:"identified_only",capture_pageview:true,capture_pageleave:true})}}
function tutorCard(t){const open=t.availability.filter(s=>!unavailable(t.id).has(s)).length;return `<article class="tutor-card"><div class="portrait" style="background:${t.color}">${portrait(t)}</div><div class="tutor-body"><div class="tutor-top"><h3>${t.name}</h3><span class="rate">$${t.rate}/hr</span></div><div class="tags">${t.subjects.map(s=>`<span class="tag">${s}</span>`).join("")}</div><div class="grade">${t.grades}</div><div class="availability">● ${open} upcoming ${open===1?"time":"times"}</div><div class="card-actions"><button class="button secondary details" data-id="${t.id}">View details</button><button class="button primary book" data-id="${t.id}">Book</button></div></div></article>`}
function renderTutors(){document.querySelector("#tutor-grid").innerHTML=tutors.map(tutorCard).join("");document.querySelectorAll(".details").forEach(b=>b.onclick=()=>showTutor(b.dataset.id));document.querySelectorAll(".book").forEach(b=>b.onclick=()=>showBooking(b.dataset.id))}
function closeButton(){return `<button class="icon-button close-modal" type="button" aria-label="Close">×</button>`}
function showTutor(id){const t=tutors.find(x=>x.id===id);capture("tutor_profile_viewed",{tutor_id:t.id,tutor_name:t.name,subjects:t.subjects});const dialog=document.querySelector("#tutor-dialog");document.querySelector("#tutor-detail").innerHTML=`<div class="modal-inner"><div class="modal-heading"><div><p class="eyebrow">Meet your tutor</p><h2>${t.name}</h2></div>${closeButton()}</div><div class="detail-meta"><div><small>Subjects</small><strong>${t.subjects.join(", ")}</strong></div><div><small>Grade levels</small><strong>${t.grades}</strong></div><div><small>Rate</small><strong>$${t.rate} / hour</strong></div></div><p class="detail-copy">${t.bio}</p><p class="availability">● ${t.availability.filter(s=>!unavailable(t.id).has(s)).length} available one-hour sessions</p><button class="button primary detail-book" type="button">See available times →</button></div>`;dialog.showModal();dialog.querySelector(".close-modal").onclick=()=>dialog.close();dialog.querySelector(".detail-book").onclick=()=>{dialog.close();showBooking(id)}}
function showBooking(id){const t=tutors.find(x=>x.id===id),slots=t.availability.filter(s=>!unavailable(id).has(s)),dialog=document.querySelector("#booking-dialog");document.querySelector("#booking-content").innerHTML=`<div class="modal-inner"><div class="modal-heading"><div><p class="eyebrow">Request a session</p><h2>Book with ${t.name}</h2></div>${closeButton()}</div>${slots.length?`<form id="booking-form"><div class="booking-summary"><strong>${t.subjects.join(" · ")} · $${t.rate}/hour</strong><span>One-hour session, pending Dana’s confirmation</span></div><div class="form-row"><label>Available time<select name="slot" required>${slots.map(s=>`<option>${s}</option>`).join("")}</select></label><label>Session format<select name="format" required><option value="online">Online</option><option value="in_person">In person</option></select></label></div><p class="location-note" hidden>📍 In-person sessions are held at <strong>123 Learning Lane (placeholder)</strong>. Dana will include arrival details in her email.</p><label>Requested subject<select name="subject" required>${t.subjects.map(s=>`<option>${s}</option>`).join("")}</select></label><div class="form-row"><label>Parent or guardian name<input name="parentName" autocomplete="name" required></label><label>Parent email<input name="email" type="email" autocomplete="email" required></label></div><div class="form-row"><label>Student’s first name<input name="studentName" autocomplete="off" required></label><label>Student’s grade<select name="grade" required><option value="">Choose grade</option>${["K",1,2,3,4,5,6,7,8,9,10,11,12].map(g=>`<option>${g}</option>`).join("")}</select></label></div><p class="hold-note">⏱ We’ll hold this time for 24 hours. Dana will confirm your session by email. Payment is invoiced separately.</p><button class="button primary" type="submit">Request this session</button></form>`:`<div class="empty">This tutor’s upcoming times are currently held or booked. Please choose another tutor.</div>`}</div>`;dialog.showModal();dialog.querySelector(".close-modal").onclick=()=>dialog.close();const form=dialog.querySelector("form");if(!form)return;let started=false;const note=form.querySelector(".location-note");form.format.onchange=()=>note.hidden=form.format.value!=="in_person";form.subject.onchange=()=>{if(!started){capture("booking_started",{tutor_id:t.id,tutor_name:t.name,subject:form.subject.value,session_format:form.format.value});started=true}};form.addEventListener("focusin",()=>{if(!started){capture("booking_started",{tutor_id:t.id,tutor_name:t.name,subject:form.subject.value,session_format:form.format.value});started=true}},{once:true});form.onsubmit=e=>submitBooking(e,t,dialog)}
function submitBooking(e,t,dialog){e.preventDefault();const f=new FormData(e.currentTarget),booking={id:crypto.randomUUID(),tutorId:t.id,tutorName:t.name,slot:f.get("slot"),format:f.get("format"),subject:f.get("subject"),parentName:f.get("parentName"),email:f.get("email"),studentName:f.get("studentName"),grade:f.get("grade"),status:"pending",createdAt:Date.now()};const items=loadBookings();if(unavailable(t.id).has(booking.slot)){showToast("Sorry, that time was just requested. Please choose another.");dialog.close();renderTutors();return}items.push(booking);saveBookings(items);capture("booking_submitted",{tutor_id:t.id,tutor_name:t.name,subject:booking.subject,session_format:booking.format,grade_band:gradeBand(booking.grade)});document.querySelector("#booking-content").innerHTML=`<div class="success"><div class="success-icon">✓</div><p class="eyebrow">Request received</p><h2>Your time is on hold!</h2><p><strong>${t.name} · ${booking.slot}</strong></p><p>Dana will confirm your session by email. We’ll hold this time for up to 24 hours while she reviews it.</p><button class="button primary close-success">Done</button></div>`;document.querySelector(".close-success").onclick=()=>{dialog.close();renderTutors()}}
function gradeBand(g){if(g==="K"||Number(g)<=5)return"elementary";if(Number(g)<=8)return"middle_school";return"high_school"}
function renderOwner(){const items=loadBookings().filter(b=>b.status!=="expired"),counts={pending:0,approved:0,declined:0};items.forEach(b=>counts[b.status]++);document.querySelector("#owner-stats").innerHTML=`<div class="stat"><strong>${counts.pending}</strong>Pending</div><div class="stat"><strong>${counts.approved}</strong>Approved</div><div class="stat"><strong>${counts.declined}</strong>Declined</div>`;const list=document.querySelector("#request-list");list.innerHTML=items.length?items.sort((a,b)=>b.createdAt-a.createdAt).map(b=>`<article class="request"><div><span class="status ${b.status}">${b.status}</span><h3>${b.studentName} · ${b.subject} with ${b.tutorName}</h3><p>${b.slot} · ${b.format==="in_person"?"In person":"Online"} · Grade ${b.grade}</p><p>Parent: ${b.parentName} · ${b.email}</p></div><div class="request-actions">${b.status==="pending"?`<button class="button secondary decide" data-id="${b.id}" data-status="approved">Approve</button><button class="button danger decide" data-id="${b.id}" data-status="declined">Decline</button>`:""}</div></article>`).join(""):`<div class="empty"><strong>No requests yet</strong><br>Submitted booking requests will appear here.</div>`;list.querySelectorAll(".decide").forEach(btn=>btn.onclick=()=>decide(btn.dataset.id,btn.dataset.status))}
function decide(id,status){const items=loadBookings(),item=items.find(b=>b.id===id);item.status=status;saveBookings(items);capture(`booking_request_${status}`,{tutor_id:item.tutorId,tutor_name:item.tutorName,subject:item.subject,session_format:item.format});renderOwner();renderTutors();showToast(status==="approved"?"Session approved":"Request declined and time released")}
function showToast(message){const el=document.querySelector("#toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2800)}
document.querySelector("#owner-open").onclick=()=>{renderOwner();document.querySelector("#owner-dialog").showModal()};document.querySelector("#owner-dialog .close-modal").onclick=()=>document.querySelector("#owner-dialog").close();document.querySelectorAll("dialog").forEach(d=>d.addEventListener("click",e=>{if(e.target===d)d.close()}));initAnalytics();renderTutors();
